// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdD3RCF73r77RS1fVELVIhoPQ-mw8yf6M',
    appId: '1:40722409823:web:c74c16189afa2f3ae02eea',
    messagingSenderId: '40722409823',
    projectId: 'soutenance-c3469',
    authDomain: 'soutenance-c3469.firebaseapp.com',
    storageBucket: 'soutenance-c3469.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBM-eyKsFH_acNg3ZRX-Ztnq4OcGiY1XUc',
    appId: '1:40722409823:android:077905e354a80a84e02eea',
    messagingSenderId: '40722409823',
    projectId: 'soutenance-c3469',
    storageBucket: 'soutenance-c3469.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJMT2fFaC4lTl_GgU13Mv6W17i1YFT2HA',
    appId: '1:40722409823:ios:d30f56a93d4ab833e02eea',
    messagingSenderId: '40722409823',
    projectId: 'soutenance-c3469',
    storageBucket: 'soutenance-c3469.appspot.com',
    iosClientId: '40722409823-fr6olt9a35o1lfu08agg9j5jr52i2dba.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJMT2fFaC4lTl_GgU13Mv6W17i1YFT2HA',
    appId: '1:40722409823:ios:47a54294439dfbf5e02eea',
    messagingSenderId: '40722409823',
    projectId: 'soutenance-c3469',
    storageBucket: 'soutenance-c3469.appspot.com',
    iosClientId: '40722409823-9l7fvfemgggnf6s8v2m2lv7tuin2k0ul.apps.googleusercontent.com',
    iosBundleId: 'com.example.project.RunnerTests',
  );
}
